const finite = (point) => Number.isFinite(point?.x) && Number.isFinite(point?.y);
const clamp = (value) => Math.max(0, Math.min(1, value));
export const defaultCorners = () => ({ topLeft:{x:.12,y:.12}, topRight:{x:.88,y:.12}, bottomRight:{x:.88,y:.88}, bottomLeft:{x:.12,y:.88} });
export function normaliseCorners(corners) { return Object.fromEntries(Object.entries(corners).map(([key, point]) => [key, { x:clamp(Number(point?.x)||0), y:clamp(Number(point?.y)||0) }])); }
export function cornersToPixels(corners, width, height) { return Object.values(corners).map(({x,y}) => ({x:x*width,y:y*height})); }
export function polygonArea(points) { return Math.abs(points.reduce((sum, point, index) => { const next=points[(index+1)%points.length]; return sum+point.x*next.y-next.x*point.y; },0))/2; }
function cross(a,b,c) { return (b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x); }
function segmentsIntersect(a,b,c,d) { const ab1=cross(a,b,c),ab2=cross(a,b,d),cd1=cross(c,d,a),cd2=cross(c,d,b); return ab1*ab2<=0 && cd1*cd2<=0; }
export function validateQuadrilateral(corners) { const p=Object.values(corners); if(p.length!==4||p.some((point)=>!finite(point))) return {valid:false,message:"PERSPECTIVE GUIDES ARE INVALID"}; if(polygonArea(p)<.002) return {valid:false,message:"PERSPECTIVE AREA IS TOO SMALL"}; if(segmentsIntersect(p[0],p[1],p[2],p[3])||segmentsIntersect(p[1],p[2],p[3],p[0])) return {valid:false,message:"PERSPECTIVE CORNERS ARE CROSSED"}; return {valid:true}; }
function solve(matrix) { const n=matrix.length; for(let col=0;col<n;col++){ let pivot=col;for(let row=col+1;row<n;row++)if(Math.abs(matrix[row][col])>Math.abs(matrix[pivot][col]))pivot=row; if(Math.abs(matrix[pivot][col])<1e-10)return null; [matrix[col],matrix[pivot]]=[matrix[pivot],matrix[col]]; const divisor=matrix[col][col];for(let i=col;i<=n;i++)matrix[col][i]/=divisor;for(let row=0;row<n;row++){if(row===col)continue;const factor=matrix[row][col];for(let i=col;i<=n;i++)matrix[row][i]-=factor*matrix[col][i];}} return matrix.map(row=>row[n]); }
export function homography(source, destination) { const rows=[]; for(let i=0;i<4;i++){const {x,y}=source[i],u=destination[i].x,v=destination[i].y;rows.push([x,y,1,0,0,0,-u*x,-u*y,u]);rows.push([0,0,0,x,y,1,-v*x,-v*y,v]);} const h=solve(rows);return h&&[h[0],h[1],h[2],h[3],h[4],h[5],h[6],h[7],1]; }
export function invertHomography(h) { const [a,b,c,d,e,f,g,i,j]=h, A=e*j-f*i,B=c*i-b*j,C=b*f-c*e,D=f*g-d*j,E=a*j-c*g,F=c*d-a*f,G=d*i-e*g,H=b*g-a*i,I=a*e-b*d,det=a*A+b*D+c*G; return Math.abs(det)<1e-12?null:[A/det,B/det,C/det,D/det,E/det,F/det,G/det,H/det,I/det]; }
export function mapPoint(h,{x,y}) { const z=h[6]*x+h[7]*y+h[8];return z?{x:(h[0]*x+h[1]*y+h[2])/z,y:(h[3]*x+h[4]*y+h[5])/z}:null; }
export function outputSize(points) { const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y); return { width:Math.max(2,Math.round((distance(points[0],points[1])+distance(points[3],points[2]))/2)), height:Math.max(2,Math.round((distance(points[0],points[3])+distance(points[1],points[2]))/2)) }; }
export function warpImageData(input,width,height,corners) { const check=validateQuadrilateral(corners);if(!check.valid)throw new Error(check.message);const source=cornersToPixels(corners,width,height),size=outputSize(source),destination=[{x:0,y:0},{x:size.width-1,y:0},{x:size.width-1,y:size.height-1},{x:0,y:size.height-1}],inverse=invertHomography(homography(source,destination));if(!inverse)throw new Error("PERSPECTIVE TRANSFORM FAILED");const output=new Uint8ClampedArray(size.width*size.height*4);for(let y=0;y<size.height;y++)for(let x=0;x<size.width;x++){const p=mapPoint(inverse,{x,y}),sx=Math.max(0,Math.min(width-1,p.x)),sy=Math.max(0,Math.min(height-1,p.y)),x0=Math.floor(sx),y0=Math.floor(sy),x1=Math.min(width-1,x0+1),y1=Math.min(height-1,y0+1),tx=sx-x0,ty=sy-y0;for(let channel=0;channel<4;channel++){const at=(px,py)=>input[(py*width+px)*4+channel],top=at(x0,y0)*(1-tx)+at(x1,y0)*tx,bottom=at(x0,y1)*(1-tx)+at(x1,y1)*tx;output[(y*size.width+x)*4+channel]=top*(1-ty)+bottom*ty;}}return {data:output,width:size.width,height:size.height}; }
// Free-transform mode: maps the original image rectangle to independently movable destination corners.
export function warpToCorners(input,width,height,corners) { const check=validateQuadrilateral(corners);if(!check.valid)throw new Error(check.message);const destination=cornersToPixels(corners,width,height),source=[{x:0,y:0},{x:width-1,y:0},{x:width-1,y:height-1},{x:0,y:height-1}],inverse=invertHomography(homography(source,destination));if(!inverse)throw new Error("WARP TRANSFORM FAILED");const output=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const p=mapPoint(inverse,{x,y});if(!p||p.x<0||p.y<0||p.x>=width||p.y>=height)continue;const x0=Math.floor(p.x),y0=Math.floor(p.y),x1=Math.min(width-1,x0+1),y1=Math.min(height-1,y0+1),tx=p.x-x0,ty=p.y-y0;for(let c=0;c<4;c++){const at=(px,py)=>input[(py*width+px)*4+c],top=at(x0,y0)*(1-tx)+at(x1,y0)*tx,bottom=at(x0,y1)*(1-tx)+at(x1,y1)*tx;output[(y*width+x)*4+c]=top*(1-ty)+bottom*ty;}}return {data:output,width,height}; }
