import assert from "node:assert/strict";
import test from "node:test";
import { writeFile } from "node:fs/promises";
import { createWorker } from "../lib/http-worker.mjs";
import { ProcessorFailure } from "../lib/processor.mjs";
const job = "11111111-1111-4111-8111-111111111111", lease = "22222222-2222-4222-8222-222222222222";
const req = (body, path = "/process-job") => new Request(`http://local${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
function setup({ processor, source = new Uint8Array([1]), upload = true, complete = true } = {}) { const calls=[]; const fetcher=async (url, init={}) => { calls.push({url,init}); if (url === "http://broker") { const body=JSON.parse(init.body); if(body.operation==="claim") return new Response(JSON.stringify({job_id:job,lease_token:lease,source:{download_url:"http://signed/source"},outputs:{small:{upload_url:"http://upload/s",token:"s"},large:{upload_url:"http://upload/l",token:"l"}}})); if(body.operation==="complete") return complete ? new Response(JSON.stringify({state:"ready"})) : new Response("x",{status:409}); return new Response(JSON.stringify({status:"failed"})); } if(url==="http://signed/source") return new Response(source); return new Response("",{status:upload?200:500}); }; return {calls, handler:createWorker({brokerUrl:"http://broker",workerToken:"token",fetcher,process:processor??(async(_i,o)=>{ await writeFile(`${o}/small.webp`,"s"); await writeFile(`${o}/large.webp`,"l"); return {small:{path:`${o}/small.webp`},large:{path:`${o}/large.webp`}}; })})}; }
test("health and strict input never contact broker", async()=>{ const {calls,handler}=setup(); const health = await handler(new Request("http://x/health")); const invalid = await handler(req({job_id:job,source:"x"})); assert.equal(health.status,200); assert.equal(invalid.status,400); assert.equal(calls.length,0); });
test("claim/download/upload/complete uses bearer and exact pairs", async()=>{ const {calls,handler}=setup(); const r=await handler(req({job_id:job})); assert.equal(r.status,200); assert.equal(calls[0].init.headers.authorization,"Bearer token"); assert.equal(JSON.parse(calls.at(-1).init.body).lease_token,lease); assert.equal(calls.filter(x=>String(x.url).startsWith("http://upload/")).length,2); });
test("claim failure does not fail invented lease; processor and upload failures use safe fail", async()=>{ let x=setup({processor:async()=>{throw new ProcessorFailure("source_byte_limit_rejected")}}); await x.handler(req({job_id:job})); assert.equal(JSON.parse(x.calls.at(-1).init.body).failure_code,"processing_failed"); x=setup({upload:false}); await x.handler(req({job_id:job})); assert.equal(JSON.parse(x.calls.at(-1).init.body).retryable,true); });
test("complete rejection is unknown and never followed by fail", async()=>{ const {calls,handler}=setup({complete:false}); const r=await handler(req({job_id:job})); assert.equal((await r.json()).error,"completion_unknown"); assert.equal(calls.filter(x=>x.url === "http://broker" && JSON.parse(x.init.body).operation==="fail").length,0); });
