import assert from "node:assert/strict";
import test from "node:test";
import { writeFile } from "node:fs/promises";
import { createWorker } from "../lib/http-worker.mjs";
import { ProcessorFailure } from "../lib/processor.mjs";
const job = "11111111-1111-4111-8111-111111111111", lease = "22222222-2222-4222-8222-222222222222";
const req = (body, path = "/process-job") => new Request(`http://local${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
function setup({ processor, source = new Uint8Array([1]), upload = true, complete = true, next = "job", logger = () => {} } = {}) { const calls=[]; const fetcher=async (url, init={}) => { calls.push({url,init}); if (url === "http://broker") { const body=JSON.parse(init.body); if(body.operation==="claim_next" && next === "empty") return new Response(null,{status:204}); if(body.operation==="claim" || body.operation==="claim_next") return new Response(JSON.stringify({job_id:job,lease_token:lease,source:{download_url:"http://signed/source",pixel_width:1285,pixel_height:2055},outputs:{small:{upload_url:"http://upload/s",token:"s"},large:{upload_url:"http://upload/l",token:"l"}}})); if(body.operation==="complete") return complete === true ? new Response(JSON.stringify({state:"ready"})) : new Response(JSON.stringify(complete),{status:complete.status}); return new Response(JSON.stringify({state:"pending"})); } if(url==="http://signed/source") return new Response(source); return new Response("",{status:upload?200:500}); }; return {calls, handler:createWorker({brokerUrl:"http://broker",workerToken:"token",fetcher,logger,process:processor??(async(_i,o)=>{ await writeFile(`${o}/small.webp`,"s"); await writeFile(`${o}/large.webp`,"l"); return {small:{path:`${o}/small.webp`,width:600,height:960,bytes:10,mimeType:"image/webp"},large:{path:`${o}/large.webp`,width:1285,height:2055,bytes:20,mimeType:"image/webp"}}; })})}; }
test("health and strict input never contact broker", async()=>{ const {calls,handler}=setup(); const health = await handler(new Request("http://x/health")); const invalid = await handler(req({job_id:job,source:"x"})); assert.equal(health.status,200); assert.equal(invalid.status,400); assert.equal(calls.length,0); });
test("claim/download/upload/complete uses bearer and exact pairs", async()=>{ const {calls,handler}=setup(); const r=await handler(req({job_id:job})); assert.equal(r.status,200); assert.equal(calls[0].init.headers.authorization,"Bearer token"); assert.equal(JSON.parse(calls.at(-1).init.body).lease_token,lease); assert.equal(calls.filter(x=>String(x.url).startsWith("http://upload/")).length,2); });
test("claim failure does not fail invented lease; processor and upload failures use safe fail", async()=>{ let x=setup({processor:async()=>{throw new ProcessorFailure("source_byte_limit_rejected")}}); await x.handler(req({job_id:job})); assert.equal(JSON.parse(x.calls.at(-1).init.body).failure_code,"processing_failed"); x=setup({upload:false}); await x.handler(req({job_id:job})); assert.equal(JSON.parse(x.calls.at(-1).init.body).retryable,true); });
test("complete rejection is unknown and never followed by fail", async()=>{ const {calls,handler}=setup({complete:false}); const r=await handler(req({job_id:job})); assert.equal((await r.json()).error,"completion_unknown"); assert.equal(calls.filter(x=>x.url === "http://broker" && JSON.parse(x.init.body).operation==="fail").length,0); });
test("completion diagnostics log safe produced and expected metadata plus a broker 422 code", async()=>{ const logs=[]; const {calls,handler}=setup({complete:{status:422,error:"wrong_dimensions",signed_url:"never-log"},logger:(line)=>logs.push(JSON.parse(line))}); const r=await handler(req({job_id:job})); assert.equal(r.status,502); assert.equal(logs.length,2); assert.deepEqual(logs[0],{event:"derivative_completion_started",job_id:job,source_width:1285,source_height:2055,small_width:600,small_height:960,large_width:1285,large_height:2055,expected_small_width:600,expected_small_height:960,expected_large_width:1285,expected_large_height:2055,small_bytes:10,large_bytes:20,small_mime:"image/webp",large_mime:"image/webp",processor_completion_reached:true}); assert.equal(logs[1].event,"derivative_completion_rejected"); assert.equal(logs[1].broker_status,422); assert.equal(logs[1].broker_error,"wrong_dimensions"); assert.equal(JSON.stringify(logs).includes("never-log"),false); assert.equal(JSON.stringify(logs).includes("http://signed/source"),false); assert.equal(calls.filter(x=>x.url === "http://broker" && JSON.parse(x.init.body).operation==="fail").length,0); });
test("drain returns 204 when no job is eligible and does not process", async()=>{ const {calls,handler}=setup({next:"empty"}); const r=await handler(new Request("http://local/drain",{method:"POST"})); assert.equal(r.status,204); assert.equal(calls.length,1); assert.equal(JSON.parse(calls[0].init.body).operation,"claim_next"); });
test("drain claims and processes exactly one job", async()=>{ const {calls,handler}=setup(); const r=await handler(new Request("http://local/drain",{method:"POST"})); assert.equal(r.status,200); assert.deepEqual(await r.json(),{job_id:job,state:"ready"}); assert.equal(calls.filter(x=>x.url === "http://broker" && JSON.parse(x.init.body).operation==="claim_next").length,1); assert.equal(calls.filter(x=>x.url === "http://broker" && JSON.parse(x.init.body).operation==="claim").length,0); });
test("drain returns success after durable retryable failure", async()=>{ const {handler}=setup({upload:false}); const r=await handler(new Request("http://local/drain",{method:"POST"})); assert.equal(r.status,200); assert.equal((await r.json()).state,"recorded_failure"); });
