-- Phase 4: publish only exact READY staging derivatives.  Legacy publication
-- operations remain readable and cleanable through their single stored path.
create or replace function private.service_claim_work_derivative_publication(target_work_id uuid, actor_account_id uuid, requested_idempotency_key uuid default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare w public.works%rowtype; op public.work_publication_operations%rowtype; candidate_operation_id uuid := gen_random_uuid(); revision_id uuid := gen_random_uuid(); image_count integer; ready_count integer; derivative_count integer; payload jsonb;
begin
 if not private.account_can_manage_work(actor_account_id,target_work_id) then raise exception 'The Work is unavailable.' using errcode='42501'; end if;
 select * into w from public.works where id=target_work_id for update;
 if not found or w.deleted_at is not null then raise exception 'The Work is unavailable.' using errcode='22023'; end if;
 if requested_idempotency_key is not null then
  select * into op from public.work_publication_operations where work_id=target_work_id and operation_kind='publish' and idempotency_key=requested_idempotency_key;
  if found then
   select coalesce(jsonb_agg(jsonb_build_object('work_image_id',d.work_image_id,'rendition_key',d.rendition_key,'staging_object_path',s.staging_object_path,'public_object_path',d.public_object_path,'mime_type',d.mime_type,'file_size',d.file_size,'copy_status',d.copy_status) order by wi.sort_order,wi.id,d.rendition_key),'[]'::jsonb) into payload from public.work_publication_derivatives d join private.work_image_derivatives s on s.id=d.source_derivative_id join public.work_images wi on wi.id=d.work_image_id where d.operation_id=op.id;
   return jsonb_build_object('operation_id',op.id,'status',op.status,'idempotent',true,'images',payload);
  end if;
 end if;
 if w.visibility='published' then return jsonb_build_object('status','published','idempotent',true,'images','[]'::jsonb); end if;
 if exists(select 1 from public.work_publication_operations where work_id=target_work_id and status in ('pending','running','cleanup_pending')) then raise exception 'A conflicting media operation is active.' using errcode='55000'; end if;
 select count(*),count(*) filter(where upload_status='ready' and original_verified_at is not null and file_size is not null) into image_count,ready_count from public.work_images where work_id=target_work_id and deleted_at is null;
 if image_count=0 then raise exception 'Publication requires at least one image.' using errcode='22023'; end if;
 if ready_count<>image_count or (select count(*) from public.work_images where work_id=target_work_id and deleted_at is null and is_cover)<>1 then raise exception 'Image processing is not complete yet.' using errcode='22023'; end if;
 select count(*) into derivative_count from private.work_image_derivatives d join public.work_images wi on wi.id=d.work_image_id where wi.work_id=target_work_id and wi.deleted_at is null and d.source_private_object_path=wi.private_object_path and d.state='ready' and d.mime_type='image/webp' and d.rendition_key in ('small','large');
 if derivative_count<>image_count*2 then raise exception 'Image processing is not complete yet.' using errcode='22023'; end if;
 insert into public.work_publication_operations(id,work_id,operation_kind,status,idempotency_key,publication_revision,actor_account_id,started_at) values(candidate_operation_id,target_work_id,'publish','running',requested_idempotency_key,revision_id,actor_account_id,statement_timestamp());
 insert into public.work_publication_operation_images(operation_id,work_image_id,private_object_path,public_object_path,mime_type,file_size) select candidate_operation_id,wi.id,wi.private_object_path,lower(w.owner_profile_id::text)||'/'||lower(target_work_id::text)||'/'||lower(revision_id::text)||'/'||lower(wi.id::text)||'/small.webp','image/webp',small.file_size from public.work_images wi join private.work_image_derivatives small on small.work_image_id=wi.id and small.source_private_object_path=wi.private_object_path and small.rendition_key='small' and small.state='ready' where wi.work_id=target_work_id and wi.deleted_at is null;
 insert into public.work_publication_derivatives(operation_id,publication_revision,work_image_id,rendition_key,source_derivative_id,public_object_path,mime_type,file_size,pixel_width,pixel_height) select candidate_operation_id,revision_id,wi.id,d.rendition_key,d.id,lower(w.owner_profile_id::text)||'/'||lower(target_work_id::text)||'/'||lower(revision_id::text)||'/'||lower(wi.id::text)||'/'||d.rendition_key::text||'.webp','image/webp',d.file_size,d.pixel_width,d.pixel_height from public.work_images wi join private.work_image_derivatives d on d.work_image_id=wi.id and d.source_private_object_path=wi.private_object_path and d.state='ready' and d.mime_type='image/webp' and d.rendition_key in ('small','large') where wi.work_id=target_work_id and wi.deleted_at is null;
 select jsonb_agg(jsonb_build_object('work_image_id',d.work_image_id,'rendition_key',d.rendition_key,'staging_object_path',s.staging_object_path,'public_object_path',d.public_object_path,'mime_type',d.mime_type,'file_size',d.file_size,'copy_status',d.copy_status) order by wi.sort_order,wi.id,d.rendition_key) into payload from public.work_publication_derivatives d join private.work_image_derivatives s on s.id=d.source_derivative_id join public.work_images wi on wi.id=d.work_image_id where d.operation_id=candidate_operation_id;
 return jsonb_build_object('operation_id',candidate_operation_id,'status','running','idempotent',false,'images',payload);
exception when unique_violation then raise exception 'A conflicting media operation is active.' using errcode='55000'; end; $$;

create or replace function private.service_record_publication_derivative_copy(target_operation_id uuid,target_image_id uuid,target_rendition private.work_image_derivative_rendition_key,actor_account_id uuid) returns boolean language plpgsql security definer set search_path='' as $$
declare updated_count integer; begin
 if not exists(select 1 from public.work_publication_operations o where o.id=target_operation_id and o.operation_kind='publish' and o.status='running' and private.account_can_manage_work(service_record_publication_derivative_copy.actor_account_id,o.work_id)) then raise exception 'The publication operation is unavailable.' using errcode='42501'; end if;
 update public.work_publication_derivatives set copy_status='created' where operation_id=target_operation_id and work_image_id=target_image_id and rendition_key=target_rendition and copy_status in ('pending','created'); get diagnostics updated_count=row_count;
 update public.work_publication_operation_images oi set copy_status='created' where oi.operation_id=target_operation_id and oi.work_image_id=target_image_id and not exists(select 1 from public.work_publication_derivatives d where d.operation_id=oi.operation_id and d.work_image_id=oi.work_image_id and d.copy_status<>'created'); return updated_count > 0; end; $$;

create function private.service_fail_work_derivative_publication(target_operation_id uuid,actor_account_id uuid,sanitized_failure_code text,cleanup_complete boolean) returns jsonb language plpgsql security definer set search_path='' as $$ declare result jsonb; begin result:=private.service_fail_work_publication(target_operation_id,actor_account_id,sanitized_failure_code,cleanup_complete); if cleanup_complete then delete from public.work_publication_derivatives where operation_id=target_operation_id; end if; return result; end; $$;
create function private.service_list_work_publication_cleanup_paths(target_operation_id uuid,actor_account_id uuid) returns jsonb language sql security definer set search_path='' as $$ select coalesce(jsonb_agg(jsonb_build_object('public_object_path',p.public_object_path)),'[]'::jsonb) from (select d.public_object_path from public.work_publication_derivatives d join public.work_publication_operations o on o.publication_revision=d.publication_revision where o.id=target_operation_id and private.account_can_manage_work(actor_account_id,o.work_id) union select oi.public_object_path from public.work_publication_operation_images oi join public.work_publication_operations o on o.id=oi.operation_id where oi.operation_id=target_operation_id and not exists(select 1 from public.work_publication_derivatives d where d.publication_revision=o.publication_revision) and private.account_can_manage_work(actor_account_id,o.work_id)) p; $$;
create function private.service_record_derivative_public_cleanup(target_operation_id uuid,actor_account_id uuid,cleanup_complete boolean,sanitized_failure_code text default null) returns jsonb language plpgsql security definer set search_path='' as $$ declare result jsonb; begin result:=private.service_record_public_cleanup(target_operation_id,actor_account_id,cleanup_complete,sanitized_failure_code); if cleanup_complete then delete from public.work_publication_derivatives where publication_revision=(select publication_revision from public.work_publication_operations where id=target_operation_id); end if; return result; end; $$;

create function public.service_claim_work_derivative_publication(target_work_id uuid,actor_account_id uuid,idempotency_key uuid default null) returns jsonb language sql security invoker set search_path='' as $$ select private.service_claim_work_derivative_publication(target_work_id,actor_account_id,idempotency_key); $$;
create function public.service_record_publication_derivative_copy(target_operation_id uuid,target_image_id uuid,target_rendition private.work_image_derivative_rendition_key,actor_account_id uuid) returns boolean language sql security invoker set search_path='' as $$ select private.service_record_publication_derivative_copy(target_operation_id,target_image_id,target_rendition,actor_account_id); $$;
create function public.service_fail_work_derivative_publication(target_operation_id uuid,actor_account_id uuid,failure_code text,cleanup_complete boolean) returns jsonb language sql security invoker set search_path='' as $$ select private.service_fail_work_derivative_publication(target_operation_id,actor_account_id,failure_code,cleanup_complete); $$;
create function public.service_list_work_publication_cleanup_paths(target_operation_id uuid,actor_account_id uuid) returns jsonb language sql security invoker set search_path='' as $$ select private.service_list_work_publication_cleanup_paths(target_operation_id,actor_account_id); $$;
create function public.service_record_derivative_public_cleanup(target_operation_id uuid,actor_account_id uuid,cleanup_complete boolean,failure_code text default null) returns jsonb language sql security invoker set search_path='' as $$ select private.service_record_derivative_public_cleanup(target_operation_id,actor_account_id,cleanup_complete,failure_code); $$;
revoke all on function private.service_claim_work_derivative_publication(uuid,uuid,uuid),private.service_record_publication_derivative_copy(uuid,uuid,private.work_image_derivative_rendition_key,uuid),private.service_fail_work_derivative_publication(uuid,uuid,text,boolean),private.service_list_work_publication_cleanup_paths(uuid,uuid),private.service_record_derivative_public_cleanup(uuid,uuid,boolean,text) from public,anon,authenticated;
grant execute on function private.service_claim_work_derivative_publication(uuid,uuid,uuid),private.service_record_publication_derivative_copy(uuid,uuid,private.work_image_derivative_rendition_key,uuid),private.service_fail_work_derivative_publication(uuid,uuid,text,boolean),private.service_list_work_publication_cleanup_paths(uuid,uuid),private.service_record_derivative_public_cleanup(uuid,uuid,boolean,text) to service_role;
revoke all on function public.service_claim_work_derivative_publication(uuid,uuid,uuid),public.service_record_publication_derivative_copy(uuid,uuid,private.work_image_derivative_rendition_key,uuid),public.service_fail_work_derivative_publication(uuid,uuid,text,boolean),public.service_list_work_publication_cleanup_paths(uuid,uuid),public.service_record_derivative_public_cleanup(uuid,uuid,boolean,text) from public,anon,authenticated;
grant execute on function public.service_claim_work_derivative_publication(uuid,uuid,uuid),public.service_record_publication_derivative_copy(uuid,uuid,private.work_image_derivative_rendition_key,uuid),public.service_fail_work_derivative_publication(uuid,uuid,text,boolean),public.service_list_work_publication_cleanup_paths(uuid,uuid),public.service_record_derivative_public_cleanup(uuid,uuid,boolean,text) to service_role;
